[book]
title = "utiles.dev"
authors = [
  "jessekrubin",
  # hopefully you!? plz help me build this thingy!
]
language = "en"
src = "src"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
smart-punctuation = true
mathjax-support = false
no-section-label = false
git-repository-url = "https://github.com/jessekrubin/utiles"
edit-url-template = "https://github.com/jessekrubin/utiles/edit/main/docs/{path}"
site-url = "https://utiles.dev" # cf
cname = "utiles.dev"
input-404 = "four-o-four.md"

[preprocessor.py_preprocessor]
command = "uv run utiles_version.py"
